spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-square-boat-aoca0h4h-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OK40WdFvYlhL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# Mail Configuration
resend.api.key=re_c1tpEyD8_NKFusih9vKVQknRAQfmFcWCv

server.http2.enabled=false
